//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MnbSoapApi.MnbSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrenciesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrenciesResult {
            get {
                return this.GetCurrenciesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrenciesResultField, value) != true)) {
                    this.GetCurrenciesResultField = value;
                    this.RaisePropertyChanged("GetCurrenciesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrencyUnitsResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrencyUnitsResult {
            get {
                return this.GetCurrencyUnitsResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrencyUnitsResultField, value) != true)) {
                    this.GetCurrencyUnitsResultField = value;
                    this.RaisePropertyChanged("GetCurrencyUnitsResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrentExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrentExchangeRatesResult {
            get {
                return this.GetCurrentExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrentExchangeRatesResultField, value) != true)) {
                    this.GetCurrentExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetCurrentExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetDateIntervalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetDateIntervalResult {
            get {
                return this.GetDateIntervalResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetDateIntervalResultField, value) != true)) {
                    this.GetDateIntervalResultField = value;
                    this.RaisePropertyChanged("GetDateIntervalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((object.ReferenceEquals(this.startDateField, value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((object.ReferenceEquals(this.endDateField, value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetExchangeRatesResult {
            get {
                return this.GetExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetExchangeRatesResultField, value) != true)) {
                    this.GetExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetInfoResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetInfoResult {
            get {
                return this.GetInfoResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetInfoResultField, value) != true)) {
                    this.GetInfoResultField = value;
                    this.RaisePropertyChanged("GetInfoResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="MnbSoap.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetCurrencies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MnbSoapApi.MnbSoap.GetCurrenciesResponse GetCurrencies(MnbSoapApi.MnbSoap.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrenciesResponse> GetCurrenciesAsync(MnbSoapApi.MnbSoap.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrencyUnits is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MnbSoapApi.MnbSoap.GetCurrencyUnitsResponse GetCurrencyUnits(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrentExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStrin" +
            "gFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDateInterval is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MnbSoapApi.MnbSoap.GetDateIntervalResponse GetDateInterval(MnbSoapApi.MnbSoap.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetDateIntervalResponse> GetDateIntervalAsync(MnbSoapApi.MnbSoap.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since the operation GetExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MnbSoapApi.MnbSoap.GetExchangeRatesResponse GetExchangeRates(MnbSoapApi.MnbSoap.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetExchangeRatesResponse> GetExchangeRatesAsync(MnbSoapApi.MnbSoap.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MnbSoapApi.MnbSoap.GetInfoResponse GetInfo(MnbSoapApi.MnbSoap.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetInfoResponse> GetInfoAsync(MnbSoapApi.MnbSoap.GetInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetCurrenciesRequestBody GetCurrencies;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(MnbSoapApi.MnbSoap.GetCurrenciesRequestBody GetCurrencies) {
            this.GetCurrencies = GetCurrencies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetCurrenciesResponseBody GetCurrenciesResponse1;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(MnbSoapApi.MnbSoap.GetCurrenciesResponseBody GetCurrenciesResponse1) {
            this.GetCurrenciesResponse1 = GetCurrenciesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetCurrencyUnitsRequestBody GetCurrencyUnits;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            this.GetCurrencyUnits = GetCurrencyUnits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(MnbSoapApi.MnbSoap.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1) {
            this.GetCurrencyUnitsResponse1 = GetCurrencyUnitsResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            this.GetCurrentExchangeRates = GetCurrentExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1) {
            this.GetCurrentExchangeRatesResponse1 = GetCurrentExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetDateIntervalRequestBody GetDateInterval;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(MnbSoapApi.MnbSoap.GetDateIntervalRequestBody GetDateInterval) {
            this.GetDateInterval = GetDateInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetDateIntervalResponseBody GetDateIntervalResponse1;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(MnbSoapApi.MnbSoap.GetDateIntervalResponseBody GetDateIntervalResponse1) {
            this.GetDateIntervalResponse1 = GetDateIntervalResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetExchangeRatesRequestBody GetExchangeRates;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(MnbSoapApi.MnbSoap.GetExchangeRatesRequestBody GetExchangeRates) {
            this.GetExchangeRates = GetExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetExchangeRatesResponseBody GetExchangeRatesResponse1;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(MnbSoapApi.MnbSoap.GetExchangeRatesResponseBody GetExchangeRatesResponse1) {
            this.GetExchangeRatesResponse1 = GetExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetInfoRequestBody GetInfo;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(MnbSoapApi.MnbSoap.GetInfoRequestBody GetInfo) {
            this.GetInfo = GetInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MnbSoapApi.MnbSoap.GetInfoResponseBody GetInfoResponse1;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(MnbSoapApi.MnbSoap.GetInfoResponseBody GetInfoResponse1) {
            this.GetInfoResponse1 = GetInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap>, MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MnbSoapApi.MnbSoap.GetCurrenciesResponse MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetCurrencies(MnbSoapApi.MnbSoap.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public MnbSoapApi.MnbSoap.GetCurrenciesResponseBody GetCurrencies(MnbSoapApi.MnbSoap.GetCurrenciesRequestBody GetCurrencies1) {
            MnbSoapApi.MnbSoap.GetCurrenciesRequest inValue = new MnbSoapApi.MnbSoap.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies1;
            MnbSoapApi.MnbSoap.GetCurrenciesResponse retVal = ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.GetCurrenciesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrenciesResponse> MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetCurrenciesAsync(MnbSoapApi.MnbSoap.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrenciesResponse> GetCurrenciesAsync(MnbSoapApi.MnbSoap.GetCurrenciesRequestBody GetCurrencies) {
            MnbSoapApi.MnbSoap.GetCurrenciesRequest inValue = new MnbSoapApi.MnbSoap.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies;
            return ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MnbSoapApi.MnbSoap.GetCurrencyUnitsResponse MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetCurrencyUnits(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public MnbSoapApi.MnbSoap.GetCurrencyUnitsResponseBody GetCurrencyUnits(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequestBody GetCurrencyUnits1) {
            MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest inValue = new MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits1;
            MnbSoapApi.MnbSoap.GetCurrencyUnitsResponse retVal = ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.GetCurrencyUnitsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrencyUnitsResponse> MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(MnbSoapApi.MnbSoap.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest inValue = new MnbSoapApi.MnbSoap.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits;
            return ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponse MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetCurrentExchangeRates(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRates(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates1) {
            MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest inValue = new MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates1;
            MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponse retVal = ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.GetCurrentExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponse> MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest inValue = new MnbSoapApi.MnbSoap.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates;
            return ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MnbSoapApi.MnbSoap.GetDateIntervalResponse MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetDateInterval(MnbSoapApi.MnbSoap.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public MnbSoapApi.MnbSoap.GetDateIntervalResponseBody GetDateInterval(MnbSoapApi.MnbSoap.GetDateIntervalRequestBody GetDateInterval1) {
            MnbSoapApi.MnbSoap.GetDateIntervalRequest inValue = new MnbSoapApi.MnbSoap.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval1;
            MnbSoapApi.MnbSoap.GetDateIntervalResponse retVal = ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.GetDateIntervalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetDateIntervalResponse> MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetDateIntervalAsync(MnbSoapApi.MnbSoap.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetDateIntervalResponse> GetDateIntervalAsync(MnbSoapApi.MnbSoap.GetDateIntervalRequestBody GetDateInterval) {
            MnbSoapApi.MnbSoap.GetDateIntervalRequest inValue = new MnbSoapApi.MnbSoap.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval;
            return ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MnbSoapApi.MnbSoap.GetExchangeRatesResponse MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetExchangeRates(MnbSoapApi.MnbSoap.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public MnbSoapApi.MnbSoap.GetExchangeRatesResponseBody GetExchangeRates(MnbSoapApi.MnbSoap.GetExchangeRatesRequestBody GetExchangeRates1) {
            MnbSoapApi.MnbSoap.GetExchangeRatesRequest inValue = new MnbSoapApi.MnbSoap.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates1;
            MnbSoapApi.MnbSoap.GetExchangeRatesResponse retVal = ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.GetExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetExchangeRatesResponse> MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetExchangeRatesAsync(MnbSoapApi.MnbSoap.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetExchangeRatesResponse> GetExchangeRatesAsync(MnbSoapApi.MnbSoap.GetExchangeRatesRequestBody GetExchangeRates) {
            MnbSoapApi.MnbSoap.GetExchangeRatesRequest inValue = new MnbSoapApi.MnbSoap.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates;
            return ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MnbSoapApi.MnbSoap.GetInfoResponse MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetInfo(MnbSoapApi.MnbSoap.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public MnbSoapApi.MnbSoap.GetInfoResponseBody GetInfo(MnbSoapApi.MnbSoap.GetInfoRequestBody GetInfo1) {
            MnbSoapApi.MnbSoap.GetInfoRequest inValue = new MnbSoapApi.MnbSoap.GetInfoRequest();
            inValue.GetInfo = GetInfo1;
            MnbSoapApi.MnbSoap.GetInfoResponse retVal = ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.GetInfoResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetInfoResponse> MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap.GetInfoAsync(MnbSoapApi.MnbSoap.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MnbSoapApi.MnbSoap.GetInfoResponse> GetInfoAsync(MnbSoapApi.MnbSoap.GetInfoRequestBody GetInfo) {
            MnbSoapApi.MnbSoap.GetInfoRequest inValue = new MnbSoapApi.MnbSoap.GetInfoRequest();
            inValue.GetInfo = GetInfo;
            return ((MnbSoapApi.MnbSoap.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
    }
}
